---
- name: Install Supervisor
  yum:
    name: supervisor
    state: present
  notify:
    restart supervisord

- name: Enable Supervisord service
  service:
    name: supervisord
    enabled: yes

- name: Update /etc/supervisord.conf to executable
  file:
    path: /etc/supervisord.conf
    mode: a+x
    state: file