---
- name: Install Supervisor
  yum:
    name: supervisor
    state: present

- name: Ensure supervisord service
  service:
    name: supervisord
    enabled: true
  when: ansible_connection != 'docker'

- name: Update /etc/supervisord.conf to executable
  file:
    path: /etc/supervisord.conf
    mode: a+x
    state: file